const fs=require('node:fs');const SYSTEM_WORDS=(()=>{for(const file of ['/usr/share/dict/american-english','/usr/share/dict/words']){try{return fs.readFileSync(file,'utf8').split(/\r?\n/)}catch{}}return[]})();const MODE_CONFIG={classic:{label:'CLASSIC',min:3,size:4,seconds:120,rule:'Free play · 2 minutes'},minimum:{label:'MINIMUM WORD',min:5,size:6,seconds:180,rule:'Minimum 5 letters'},sudden:{label:'SUDDEN DEATH',min:3,size:5,seconds:180,rule:'One invalid word ends the round'},race:{label:'RACE MODE',min:3,size:4,seconds:240,rule:'First to 500 points wins'},coop:{label:'CO-OP',min:3,size:4,seconds:120,rule:'Shared team score · find words together'},dirty:{label:'DIRTY MODE · 18+',min:3,size:5,seconds:180,rule:'Opt-in adult dictionary'}};
const COMMON_WORDS='CAT DOG MAP SUN RED FOX STAR STARE STONE LINE LINES LION PLACE SPACE MOUSE MUSES STREAM WORDS RUSH BRAIN TRACE FIRE FINE SCORE RAIN TRAIN STAIR TONE NOTE RATE PLANE PLANT HEART HOUSE'.split(' ');const ADULT_WORDS='ASS BITCH COCK DAMN DICK HELL PISS SHIT SLUT TIT'.split(' ');const ADULT_SET=new Set(ADULT_WORDS);const LETTER_BAG='EEEEEEEEEEEEAAAAAAAARRRRRRIIIIIIIIOOOOOOOONNNNNNTTTTTTLLLLSSSSUUUUDDDDGGGBBCCMMPPHHFFVVWWYYKJXQZ';
function normalizeWords(words){return[...new Set((words||[]).map(word=>String(word).trim().toUpperCase()).filter(word=>/^[A-Z]{3,}$/.test(word)))]}function neighbors(index,size){const row=Math.floor(index/size),col=index%size,result=[];for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++){const r=row+dr,c=col+dc;if((dr||dc)&&r>=0&&c>=0&&r<size&&c<size)result.push(r*size+c)}return result}
function findPlacement(word,size,cells){for(const start of[...Array(size*size).keys()].sort(()=>Math.random()-.5)){if(cells[start]&&cells[start]!==word[0])continue;const path=[start],used=new Set(path);function walk(){if(path.length===word.length)return true;for(const next of neighbors(path.at(-1),size).filter(index=>!used.has(index)&&(!cells[index]||cells[index]===word[path.length])).sort(()=>Math.random()-.5)){path.push(next);used.add(next);if(walk())return true;path.pop();used.delete(next)}return false}if(walk())return path}return null}
function hasPath(board,size,word){for(let start=0;start<board.length;start++){if(board[start]!==word[0])continue;const used=new Set([start]);function walk(index,depth){if(depth===word.length)return true;for(const next of neighbors(index,size))if(!used.has(next)&&board[next]===word[depth]){used.add(next);if(walk(next,depth+1))return true;used.delete(next)}return false}if(walk(start,1))return true}return false}
function generateBoard(size,lexicon,options={}){const words=normalizeWords(lexicon).filter(word=>word.length<=Math.min(12,size*size));const dirtyLexicon=ADULT_WORDS.every(word=>words.includes(word));const preferred=new Set(normalizeWords(options.preferredWords||[]).concat(dirtyLexicon?ADULT_WORDS:[]));for(let attempt=0;attempt<40;attempt++){const cells=Array(size*size).fill('');const targets=[3,4,5,6].map((length,bucket)=>{const matches=word=>bucket===3?word.length>=length:word.length===length;const preferredCandidates=words.filter(word=>preferred.has(word)&&matches(word));const candidates=preferredCandidates.length?preferredCandidates:words.filter(matches);return candidates[Math.floor(Math.random()*candidates.length)]}).filter(Boolean).sort((a,b)=>b.length-a.length);targets.forEach(word=>{const path=findPlacement(word,size,cells);if(path)path.forEach((index,offset)=>{cells[index]=word[offset]})});const board=cells.map(char=>char||LETTER_BAG[Math.floor(Math.random()*LETTER_BAG.length)]);const coverage=[3,4,5,6].filter((length,bucket)=>words.some(word=>(bucket===3?word.length>=length:word.length===length)&&hasPath(board,size,word)));if(coverage.length>=Math.min(4,words.length?4:0))return board}return Array.from({length:size*size},()=>LETTER_BAG[Math.floor(Math.random()*LETTER_BAG.length)])}
function createLexicon(mode,customWords=[]){return normalizeWords([...COMMON_WORDS,...SYSTEM_WORDS.filter(word=>!ADULT_SET.has(String(word).toUpperCase())),...customWords,...(mode==='dirty'?ADULT_WORDS:[])])}function validateSubmission({board,size,word,path,mode,found,customWords}){const config=MODE_CONFIG[mode]||MODE_CONFIG.classic,cleanWord=String(word||'').toUpperCase(),indexes=Array.isArray(path)?path.map(Number):[],validPath=indexes.length===cleanWord.length&&indexes.every((index,position)=>Number.isInteger(index)&&index>=0&&index<board.length&&board[index]===cleanWord[position]&&(position===0||neighbors(indexes[position-1],size).includes(index))&&indexes.indexOf(index)===position),valid=cleanWord.length>=config.min&&createLexicon(mode,customWords).includes(cleanWord)&&validPath&&!found.has(cleanWord);return{valid,word:cleanWord,points:valid?cleanWord.length*cleanWord.length:0,reason:validPath?(found.has(cleanWord)?'duplicate':'dictionary'):'path'}}
module.exports={MODE_CONFIG,COMMON_WORDS,ADULT_WORDS,normalizeWords,neighbors,hasPath,generateBoard,createLexicon,validateSubmission};



